site_name: Corsair
site_url: https://corsair-csr.github.io/
site_description: CLI tool and Python library designed to manage CSR maps for HDL projects
repo_url: https://github.com/esynr3z/corsair

plugins:
  - search
  - social
  - blog
  - mkdocstrings
  - git-revision-date-localized:
      enable_creation_date: true
  - exclude:
      glob:
        - "assets/private/*"
        - "*.sh"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

extra:
  version:
    provider: mike

extra_css:
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/logo-white-outline.svg
  favicon: assets/images/favicon.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.action.edit
    - content.code.copy
    - search.suggest
    - search.highlight
    - search.share

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: indigo
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - abbr
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

nav:
  - Getting Started:
      - index.md
      - installation.md
      - first-steps.md
      - contributing.md
      - changelog.md
  - Concepts:
      - concepts/index.md
      - concepts/philosophy.md
      - concepts/workflow.md
      - concepts/build-specification.md
      - concepts/loaders.md
      - concepts/register-model.md
      - concepts/generators.md
      - concepts/customization.md
      - concepts/file-confidence.md
  - Build File:
      - build-file/index.md
      - Loaders:
          - build-file/loaders/index.md
      - Generators:
          - build-file/generators/index.md
          - build-file/generators/sv.md
          - build-file/generators/sv-package.md
          - build-file/generators/verilog.md
          - build-file/generators/verilog-header.md
          - build-file/generators/vhdl.md
          - build-file/generators/markdown.md
          - build-file/generators/asciidoc.md
          - build-file/generators/c-header.md
          - build-file/generators/custom.md
  - Register File:
      - register-file/index.md
      - register-file/yaml.md
      - register-file/json.md
      - register-file/toml.md
      - register-file/custom.md
  - CLI: cli.md
  - API: api.md
  - Hardware:
      - hardware/index.md
      - Fields:
          - hardware/fields/index.md
      - Protocols:
          - hardware/protocols/index.md
  - Cookbook:
      - cookbook/index.md
      - Using CLI:
          - cookbook/cli/create-project.md
      - Using API:
          - cookbook/api/custom-flow.md
  - Blog:
      - blog/index.md
