name: Devcontainer

on:
  push:
    branches:
      - dev2 # FIXME: replace with `master` after merging
  workflow_dispatch: {} # allow manual triggering

jobs:
  build:
    name: Build devcontainer image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: esynr3z
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/esynr3z/corsair-workspace
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: always
