name: Tests & Checks

on:
  push:
    branches:
      - dev2 # FIXME: replace with `master` after merging
  pull_request:
    branches:
      - '**'

env:
  PY_COLORS: "1"

jobs:
  test:
    name: Python ${{ matrix.python-version }} tests & checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # need the entire commit history for checking commits

      - name: Install Python ${{ matrix.python-version }} and project dependencies
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: |
            uv venv -p ${{ matrix.python-version }}
            uv sync --all-extras --dev

      - name: Check branch commits
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: |
            uv run poe check-commits

      - name: Check generated files
        uses: devcontainers/ci@v0.3
        if: always()
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: |
            uv run pre-commit run uv-lock --all-files
            uv run pre-commit run check-yaml --all-files
            uv run pre-commit run check-json --all-files
            uv run pre-commit run check-toml --all-files
            uv run pre-commit run schemas --all-files

      - name: Check Python code format
        uses: devcontainers/ci@v0.3
        if: always()
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe check-format

      - name: Lint Python code
        uses: devcontainers/ci@v0.3
        if: always()
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe lint

      - name: Do type checking for Python code
        uses: devcontainers/ci@v0.3
        if: always()
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe check-types

      - name: Run all tests
        uses: devcontainers/ci@v0.3
        if: always()
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe test
