name: Tests & Checks

on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - '**'

env:
  PY_COLORS: "1"
  DEVCONTAINER_CONFIG_PATH: ".devcontainer"

jobs:
  test:
    # The action itself runs on ubuntu-latest, but the commands execute inside the dev container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Use the devcontainers/ci action to run steps inside the container
    - name: Install the project in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv sync --all-extras --dev

    - name: Check branch commits in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv run poe check-commits

    - name: Check Python code format in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv run poe check-format

    - name: Lint Python code in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv run poe lint

    - name: Do type checking for Python code in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv run poe check-types

    - name: Run tests in dev container
      uses: devcontainers/ci@v0.3
      with:
        configPath: ${{ env.DEVCONTAINER_CONFIG_PATH }}
        run: uv run poe test
