name: pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-xdist
        pip install pyyaml jinja2 wavedrom
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y libxtst6:i386 libxft2:i386
        wget https://download.altera.com/akdlm/software/acdsinst/20.1std/711/ib_installers/ModelSimSetup-20.1.0.711-linux.run
        chmod +x ModelSimSetup-20.1.0.711-linux.run
        ./ModelSimSetup-20.1.0.711-linux.run --mode unattended --accept_eula 1 --installdir $HOME/ModelSim-20.1.0 --unattendedmodeui none
        echo "$HOME/ModelSim-20.1.0/modelsim_ase/bin" >> $GITHUB_PATH
    - name: Test package
      run: |
        pytest -v -n auto
    - name: Upload build artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: /tmp
