name: Tests & Checks

on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - '**'

env:
  PY_COLORS: "1"

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/esynr3z/corsair-workspace
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: always

  test:
    # The action itself runs on ubuntu-latest, but the commands execute inside the dev container
    runs-on: ubuntu-latest
    needs: build-container
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10'] #'3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python ${{ matrix.python-version }} and project dependencies
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: |
            uv venv -p ${{ matrix.python-version }}
            uv sync --all-extras --dev

      - name: Check branch commits
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe check-commits

      - name: Check Python code format
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe check-format

      - name: Lint Python code
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe lint

      - name: Do type checking for Python code
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe check-types

      - name: Run all tests
        uses: devcontainers/ci@v0.3
        continue-on-error: true
        with:
          cacheFrom: ghcr.io/esynr3z/corsair-workspace
          push: never
          runCmd: uv run poe test
