name: Tests & Checks

on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - '**'

env:
  PY_COLORS: "1"

jobs:
  test:
    # The action itself runs on ubuntu-latest, but the commands execute inside the dev container
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10'] #'3.11', '3.12', '3.13']

    name: Python ${{ matrix.python-version }} Tests
    steps:
    - uses: actions/checkout@v4

    # Use the devcontainers/ci action to run steps inside the container
    - name: Install Python ${{ matrix.python-version }} and project dependencies
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          uv venv -p ${{ matrix.python-version }}
          uv sync --all-extras --dev

    - name: Check branch commits
      uses: devcontainers/ci@v0.3
      with:
        runCmd: uv run poe check-commits

    - name: Check Python code format
      uses: devcontainers/ci@v0.3
      with:
        runCmd: uv run poe check-format

    - name: Lint Python code
      uses: devcontainers/ci@v0.3
      with:
        runCmd: uv run poe lint

    - name: Do type checking for Python code
      uses: devcontainers/ci@v0.3
      with:
        runCmd: uv run poe check-types

    - name: Run tests
      uses: devcontainers/ci@v0.3
      with:
        runCmd: uv run poe test
